### PR TITLE
files for new oi_cycle_separation

### PR DESCRIPTION
**Pull request by hulsiejames**
Example output for a 2.5km buffer around Leeds 

Screenshot from 2022-09-06 18-34-31

This function assess the level of separation provided for cycling infrastructure, adn where possible indicates compliance with LTN1/20. 

The levels of separation are:
- Mixed Traffic 
- Cycle Lanes (cycleway="lane") 
- Protected Cycling (highway = "cycleway" | cycleway = "path|track")

### CODE REVIEW

**Review by Robinlovelace — APPROVED** [review]
Great work @hulsiejames, this is a useful categorisation and takes us closer to LTN 1/20, right?

**Comment by hulsiejames** [comment]
Yes, this allows us to group/categorise cycling infrastructure to then compare against maxspeeds and potential widths (where available).

**Comment by Robinlovelace** [comment]
And final stage to tidy up @hulsiejames: delete the branch :shower:

**Comment by hulsiejames** [comment]
Oops! Though I had clicked that, thank you for the spot!

**Pull request merged**
