### PR TITLE
new national and local cycle routes function

### PR DESCRIPTION
**Pull request by hulsiejames**
New function that looks at OSM data obtained from `osmextract::oe_get()` for the "lines" (ways) and "multilinestring" (relations) data layers. 

Currently assesses the presence of National Cycle Networks (ncns) and Local cycle Networks (lcns) looking at lcn & ncn tags. 

If a way is part of, or a relation is a ncn/lcn, values are added to a new column `openinfra_cycle_routes` on the type of route (ncn/lcn) and route name (lcn_ref/ncn_ref). 

Additionally, if input, the `cycle_network` field is also added, comonly used for more granular route parts. 

Further justifiaction on included tags can be found here: https://udsleeds.github.io/openinfra/articles/proposed_cycle_routes.html

For an exmaple of the function (without needing this PR), pull the main repo and see [proposed_oi_cycle_routes.R](https://github.com/udsleeds/openinfra/blob/main/test-code/proposed_oi_cycle_routes.R) 
Note: the above script downloads england-latest.osm.pbf. If this is too long, you may use the recently added example_data_rels and example_data for Leeds relations & ways data respectively

An example visualisation of English lcn/ncns from the above script: 
Screenshot from 2022-10-14 17-23-04

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Doesn't look very comprehensive compared with this map I made, starting with osmextract: https://twitter.com/robinlovelace/status/1570127636051144704

**Review by Robinlovelace — COMMENTED** [review]
Looks good but does it return the complete NCN? Not as far as I can tell.

**Comment by hulsiejames** [comment]
Ahh yes - this may be more complex than I initially thought. 

This function essentially relies on the presence of the `ncn` & or `lcn` tag to assess if a way/relation is part of a national / local cycleway, with other tags used to classify parts of routes. 

However, it seems not all realtions are tagged this way :( 
See NCN 1 for example below:
Screenshot from 2022-10-15 15-17-00
Which is tagged: 
```
type = route     #the relation is a route
route = bicycle #the route relation is for a bicycle
network = ncn  #the route relation is for a NCN cycle network
ref = 1              #the ncn route relation is for NCN 1

#Additional info (Not essential but useful) 
Name = NCN National Route 1                      #Useful descriptive name
cycle_network = UK:National Cycle Network # Specific route the relation belongs to
operator = sustrans                                        # Operator of the route
```
**Solution(s)**
I think the `network` key needs to be considered as the same importance that lcn & ncn currently are.

From the function for lcn detection from relations (same code for ncn's): 
```
      (type == "route" & route == "bicycle") & 
        # relation must be related to lcns
        ((!is.na(lcn)) & (lcn != "no")) & 
        # Relation must be lcn network (or NA if not entered)
        (is.na(network) | network == "lcn")
      ~ paste("lcn:", lcn, lcn_ref, name, cycle_network),

# Clearly the `network` key is as useful as ncn/lcn keys - incorporate this below

        (type == "route" & route == "bicycle") & 
        # relation must be related to lcns
        ( ((!is.na(lcn)) & (lcn != "no")) | (!is.na(network))&(network!="no") ) & 
        # Relation must be lcn network (or NA if not entered)
        (is.na(network) | network == "lcn")
      ~ paste("lcn:", lcn, lcn_ref, name, cycle_network),

```

I'll have a play and update when I get a moment!

**Comment by hulsiejames** [comment]
[6b19c33](https://github.com/udsleeds/openinfra/pull/148/commits/6b19c336854027ab358776d8c83a7bfe7d9f97c6) includes the network tag. 

Networks (specifically NCNs) are now more comprehensive. 

England NCNs

Screenshot from 2022-10-16 14-53-32

England LCNs

Screenshot from 2022-10-16 14-56-22

England LCNs & NCNs
Screenshot from 2022-10-16 14-58-37

**Comment by hulsiejames** [comment]
Coverage should be much more comprehensive now. 

The issue was in parsing the relation layers (oe_get argument layer = "multilinestring" | "other_relations"). 

NCN & LCN routes can be obtained from ways (legacy tagging) using the `ncn`/`lcn` keys, but when parsing relations the `network` key is used to define whether a route is lcn/ncn or another route. 

The current version of the function parses relations for **bicycle** routes **only** (that is: `type=route` & **`route=bicycle`**), as opposed to mountainbike routes (`type=route & route=mtb`)

**Comment by Robinlovelace** [comment]
This looks really good @hulsiejames, great work! You joining our mini hack at 15:00 in ITS today?

**Comment by hulsiejames** [comment]
Yes, looking forward to it! Just about to set off via a late lunch stop and wait in ITS for the start!

**Pull request merged**
